version: '3'
services:

  backend:
    container_name: backend
    build:
      context: ./.docker/
      dockerfile: php.dockerfile
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 80:80
    volumes:
      - ./backend/:/var/www/html/

  frontend:
    container_name: frontend
    build:
      context: ./.docker/
      dockerfile: php.dockerfile
    depends_on:
      - mysql
    links:
      - mysql:db
      - backend:api
    ports:
      - 8080:80
    volumes:
      - ./shitty-frontend/:/var/www/html/
  
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tbc_db
      - MYSQL_USER=tbc_user
      - MYSQL_PASSWORD=tbc_pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 8081:80

  # swagger_editor:
  #   container_name: swagger-editor
  #   image: swaggerapi/swagger-editor
  #   ports:
  #     - 8082:8080

  # swagger_ui:
  #   container_name: swagger-ui
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - 8083:8080

volumes:
  mysql_data:
